#!/bin/sh
#
# svnclean -- delete all files not under version control of Subversion
#
# Synopsis:
#   svnclean [-L] [-C]
#
# Specify -C to commit the operation.  Otherwise svnclean will just print
# the files it would delete.  Unless -L is specified, symbolic links are
# left alone.
#

getfiles() {
	svn status --no-ignore | sed -ne 's/^[?I] \+//p' \
	| while read fname;
	do
		[ $1 = "no" -a -L "$fname" ] \
			|| echo "$fname";
	done
}

if [ "x$1" = "x-L" ];
then
	opt_symlinks="yes";
	shift;
else
	opt_symlinks="no";
fi

if [ "x$1" = "x" ];
then
	getfiles $opt_symlinks;
elif [ "x$1" = "x-C" ];
then
	getfiles $opt_symlinks | xargs -- rm -rf;
else
	echo "svnclean: $1: unknown option" >&2;
fi

# End of svnclean
