#!/bin/sh
#
# lsmp3 -- display ID3v1 tags of MP3 files using mp3info(1)
#
# Synopses:
#   lsmp3 [<mp3-files>]
#     Display the title of <mp3-files>.
#   lsmp3 -a [<mp3-files>]
#     Display the artist, album, year and genre of <mp3-files>.
#
# If no <mp3-files> are specified, the list of files will be searched for
# in the ./playlist or any *.m3u file, if any exists.  If not, information
# about *.mp3, *.MP3 and *.Mp3 files will be displayed.

# mp3info(1) can be told the information to display by specifying a
# printf()-style format argument.  Set one depending on whether to
# display album-info (-a) or song-info.
if [ "x$1" = "x-a" ];
then
	# <track_no>. <artist>: <album> (<year>, <genre>)
	fmt='%2n. %a: %l (%y, %g)\n';
	shift;
else	# <track_no>. <title>
	fmt='%2n. %t\n';
fi

# Which files to display information about?
# Those located in playlists?
if [ $# -eq 0 ];
then
	ifs="$IFS";
	IFS="
";
	for list in playlist *.m3u *.M3U *.M3u;
	do	# Replace DOS \r\n with \n.
		[ -f "$list" ] && set -- "$@" `tr -d '\r' < "$list"`;
	done
	IFS="$ifs";
fi

# *.mp3 files in the current directory?
if [ $# -eq 0 ];
then
	for mp3 in *.Mp3 *.MP3 *.mp3;
	do
		[ -f "$mp3" ] && set -- "$@" "$mp3";
	done
fi

# Exit if didn't find any files.
[ $# -gt 0 ] || exit 0;

# Run mp3info through the list of files with the appripriate $fmt.
exec mp3info -p "$fmt" "$@";

# End of lsmp3
